name: deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install npm packages
        run: npm install
      - name: Build Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          cache_froms: danushka96/tubemate/tubemate:latest
          registry: docker.pkg.github.com
          repository: danushka96/tubemate/tubemate
          tag_with_ref: true
